name: horas

on:
  push:
    branches: [main]

jobs:  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    

    steps: 
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Setup de Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13.3'

      - name: Instalar dependencias
        run: pip install pytz

      - name: Run del script      
        run: python ./horas_paises.py

      - name: Commit y Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Paises horas ok
          commit_user_name: Beatriz Lopez [GitHub Actions]
          
